version: "3"

services:

    # MySQL
    db:
        build:
            context: ./dockerfiles
            dockerfile: db.dockerfile
        image: ${PROJECT_NAME}/mysql
        container_name: ${PROJECT_NAME}-db
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        networks:
            - inner
        restart: unless-stopped

    # PHP + Apache
    app:
        build:
            context: ./dockerfiles
            dockerfile: wordpress.dockerfile
        image: ${PROJECT_NAME}/app
        container_name: ${PROJECT_NAME}-app
        volumes:
            - ./code:/var/www/html
            - ./config/php:/usr/local/etc/php
        expose:
            - 80
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            VIRTUAL_HOST: ${PROJECT_NAME}.${PROJECT_DOMAIN}
            VIRTUAL_PORT: 80
            XDEBUG_CONFIG: "remote_host=host.docker.internal mode=debug remote_port=${XDEBUG_REMOTE_PORT}"
            PHP_IDE_CONFIG: "serverName=${PROJECT_NAME}"
        networks:
            - inner
            - nginx-proxy
        extra_hosts:
            host.docker.internal: host-gateway
        restart: unless-stopped
    
networks:
    
    # Inner bridge network 
    inner:
        driver: bridge
        
    # Common network for other services
    nginx-proxy:
        external: true
        name: nginx-proxy